backend:backend:
  name: github
  repo: omarsib/art-heaven-museum
  branch: main

media_folder: "images" # المجلد الذي ستحفظ فيه الصور
public_folder: "images"

collections:
  - name: "winners"
    label: "الفائزين"
    folder: "data/winners"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "اسم الفائز", name: "title", widget: "string" }
      - { label: "المركز", name: "rank", widget: "select", options: ["الأول", "الثاني", "الثالث"] }
      - { label: "الصورة", name: "image", widget: "image" }